In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu

# Centrosome analysis

Channel 1 - centrin?
Channel 2 - gamma tubulin?

## Parameters

In [2]:
DIR = "/mnt/c/users/helen/Desktop/test"

## Data loading

In [3]:
from utils import load_data

In [4]:
df = load_data(DIR)

In [5]:
df

,,Image,Cell,Channel number,ROI,File,Path
0,1,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,1,1,0424-0565,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
1,2,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,1,2,0309-0430,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
2,3,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,1,2,0307-0439,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
3,4,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,2,1,0481-0492,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
4,5,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,2,1,0492-0493,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
5,6,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,2,2,0482-0430,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
6,1,hct116_4_pcdna_vacio_+_satr2__pcnt-gamma_tub-11,1,1,0465-0213,results_hct116_4_pcdna_vacio_+_satr2__pcnt-gam...,/mnt/c/users/helen/Desktop/test/results_hct116...
7,2,hct116_4_pcdna_vacio_+_satr2__pcnt-gamma_tub-11,1,2,0456-0232,results_hct116_4_pcdna_vacio_+_satr2__pcnt-gam...,/mnt/c/users/helen/Desktop/test/results_hct116...

In [15]:
ch1 = df[df['Channel number'] == 1]
ch2 = df[df['Channel number'] == 2]

In [16]:
ch1

,,Image,Cell,Channel number,ROI,File,Path
0,1,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,1,1,0424-0565,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
3,4,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,2,1,0481-0492,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
4,5,2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04,2,1,0492-0493,results_2_hct116_wt_pcdna_vacio__pcnt-gamma_tu...,/mnt/c/users/helen/Desktop/test/results_2_hct1...
6,1,hct116_4_pcdna_vacio_+_satr2__pcnt-gamma_tub-11,1,1,0465-0213,results_hct116_4_pcdna_vacio_+_satr2__pcnt-gam...,/mnt/c/users/helen/Desktop/test/results_hct116...

## Data processing

In [19]:
roi_counts_1 = ch1.groupby(['Image','Cell'])['ROI'].count()
roi_counts_2 = ch2.groupby(['Image','Cell'])['ROI'].count()

In [21]:
roi_counts_2

Image                                            Cell
2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04       1       2
                                                 2       1
hct116_4_pcdna_vacio_+_satr2__pcnt-gamma_tub-11  1       1
Name: ROI, dtype: int64

In [20]:
roi_counts_1

Image                                            Cell
2_hct116_wt_pcdna_vacio__pcnt-gamma_tub-04       1       1
                                                 2       2
hct116_4_pcdna_vacio_+_satr2__pcnt-gamma_tub-11  1       1
Name: ROI, dtype: int64